spring:
  application:
    name: trade-systems

#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: http://localhost:8083/eureka
    #register-with-eureka: true
    #fetch-registry: true
    #healthcheck:
     # enabled: true
  # preferIpAddress: true

server.port: 8088

kafka:
  bootstrapAddress: dory-01.srvs.cloudkafka.com:9094,dory-02.srvs.cloudkafka.com:9094,dory-03.srvs.cloudkafka.com:9094
  feed:
    topic:
      name: qyplzit6-default
      userName: qyplzit6
      password: pSJSf6GKc5KCFoLfcbUkaETrmzyAdw_s
  #consumer: trade-consumer