DROP TABLE IF EXISTS TRADE_STORE;
   CREATE TABLE TRADE_STORE (
     ID INT AUTO_INCREMENT  PRIMARY KEY,
     TRADE_ID VARCHAR(10) NOT NULL,
     VERSION INT NOT NULL,
     COUNTER_PARTY_ID VARCHAR(25) NOT NULL,
     BOOK_ID VARCHAR(250) NOT NULL,
     EXPIRED_FLAG CHAR(1) NOT NULL,
     MATURITY_ON DATE NOT NULL,
     CREATED_ON DATE DEFAULT CURRENT_DATE NOT NULL
   );

INSERT INTO TRADE_STORE (TRADE_ID, VERSION, COUNTER_PARTY_ID,BOOK_ID,EXPIRED_FLAG,MATURITY_ON,
CREATED_ON) VALUES
  ('T1', 1, 'CP-1','B1','N',TO_DATE('20-MAY-2020','DD-MON-YYYY'),CURRENT_DATE),
  ('T2', 2, 'CP-2','B1','N',TO_DATE('20-MAY-2021','DD-MON-YYYY'),CURRENT_DATE),
  ('T2', 1, 'CP-1','B1','N',TO_DATE('20-MAY-2021','DD-MON-YYYY'),CURRENT_DATE),
  ('T3', 3, 'CP-3','B2','N',TO_DATE('20-MAY-2014','DD-MON-YYYY'),CURRENT_DATE),
  ('T4', 3, 'CP-3','B2','Y',TO_DATE('20-MAY-2014','DD-MON-YYYY'),CURRENT_DATE);
